### ISSUE TITLE
RejectedExecutionException on trying to unsubscribe from websocket when quiting

### ISSUE THREAD

**Issue by fqqb** [yamcs/yamcs-studio#10]
Sometimes get this stacktrace when quitting app

```
2015-05-23 09:19:21.545 WARNING [Thread 1] org.yamcs.api.YamcsConnector (disconnect) - Disconnection requested
2015-05-23 09:19:21.563 INFO [Thread 84] org.yamcs.studio.core.pvmanager.ParameterChannelHandler (disconnect) - Disconnect called on Background
Exception in thread "Thread-10" java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:703)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:296)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:691)
	at io.netty.util.concurrent.AbstractEventExecutorGroup.execute(AbstractEventExecutorGroup.java:114)
	at org.yamcs.api.ws.WebSocketClient.sendRequest(WebSocketClient.java:147)
	at org.yamcs.studio.core.WebSocketRegistrar.sendMergedRequests(WebSocketRegistrar.java:103)
	at org.yamcs.studio.core.WebSocketRegistrar.lambda$0(WebSocketRegistrar.java:60)
	at org.yamcs.studio.core.WebSocketRegistrar$$Lambda$20/1219812579.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

Workaround could be to catch that exception, but seems like we should manage this better.

**Comment by fqqb** [comment]
closing because outdated i believe. Last time i saw this was ages ago, and code has undergone many changes since then.
