### ISSUE TITLE
got a ConcurrentModificationException

### ISSUE THREAD

**Issue by fqqb** [yamcs/yamcs-studio#13]
During startup on a slow machine, clicked from Stack quickly to History, and got this beauty:

```
2015-05-26 16:00:23.748 INFO [Thread 35] org.yamcs.studio.core.pvmanager.ParameterChannelHandler (connect) - Connect called on DCSS_BatteryVoltage1
2015-05-26 16:00:23.756 INFO [Thread 35] org.yamcs.studio.core.pvmanager.ParameterChannelHandler (connect) - Connect called on DCSS_BatteryTemperature1
2015-05-26 16:00:23.758 INFO [Thread 35] org.yamcs.studio.core.pvmanager.ParameterChannelHandler (connect) - Connect called on DCSS_BusVoltage
2015-05-26 16:00:23.758 INFO [Thread 35] org.yamcs.studio.core.pvmanager.ParameterChannelHandler (connect) - Connect called on DCSS_BusCurrent
2015-05-26 16:00:23.758 INFO [Thread 35] org.yamcs.studio.core.pvmanager.ParameterChannelHandler (connect) - Connect called on DCSS_BatteryVoltage2
2015-05-26 16:00:23.759 INFO [Thread 35] org.yamcs.studio.core.pvmanager.ParameterChannelHandler (connect) - Connect called on DCSS_BatteryTemperature2
2015-05-26 16:00:24.359 INFO [Thread 1] org.yamcs.studio.ui.commanding.stack.CommandStackStateProvider (refreshState) - Fire new stack state {org.yamcs.studio.ui.commanding.stack.state.empty=true, org.yamcs.studio.ui.commanding.stack.state.remaining=false, org.yamcs.studio.ui.commanding.stack.state.armed=false, org.yamcs.studio.ui.commanding.stack.state.executionStarted=false}
2015-05-26 16:00:26.037 INFO [Thread 1] org.yamcs.studio.ui.processor.ProcessorStateProvider (updateState) - Fire new processing state {org.yamcs.studio.ui.processor.state.processing=, org.yamcs.studio.ui.processor.state.replay=false}
2015-05-26 16:00:26.379 INFO [Thread 35] org.yamcs.studio.core.pvmanager.ParameterChannelHandler (connect) - Connect called on DCSS_Theta
2015-05-26 16:00:26.389 INFO [Thread 35] org.yamcs.studio.core.pvmanager.ParameterChannelHandler (connect) - Connect called on DCSS_Psi
2015-05-26 16:00:32.513 INFO [Thread 31] org.yamcs.studio.core.YamcsLoginModule (login) - 
2015-05-26 16:00:32.514 INFO [Thread 31] org.yamcs.studio.core.YamcsLoginModule (authenticate) - yamcs login, authenticating operator/password
2015-05-26 16:00:33.770 INFO [Thread 31] org.yamcs.studio.core.YamcsLoginModule (commit) - yamcs login, commit
2015-05-26 16:00:33.791 INFO [Thread 31] org.yamcs.studio.core.YamcsPlugin (connect) - Connecting to Yamcs server, node 2
2015-05-26 16:00:33.810 INFO [Thread 31] org.yamcs.studio.core.YamcsPlugin (setConnectionStatus) - Current connection status: Connecting
2015-05-26 16:00:33.851 INFO [Thread 31] org.yamcs.api.ws.WebSocketClient (createBootstrap) - WebSocket Client connecting
2015-05-26 16:00:33.895 INFO [Thread 46] org.yamcs.api.ws.WebSocketClientHandler (channelRead0) - WebSocket Client connected!!
2015-05-26 16:00:35.044 INFO [Thread 46] org.yamcs.studio.core.pvmanager.ParameterChannelHandler (processConnectionInfo) - processConnectionInfo called on DCSS_BusCurrent
2015-05-26 16:00:35.044 INFO [Thread 46] org.yamcs.studio.core.pvmanager.ParameterChannelHandler (disconnect) - Disconnect called on DCSS_BusCurrent
2015-05-26 16:00:35.044 INFO [Thread 46] org.yamcs.studio.core.pvmanager.ParameterChannelHandler (connect) - Connect called on DCSS_BusCurrent
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at org.yamcs.studio.core.YamcsPlugin.setupConnections(YamcsPlugin.java:183)
	at org.yamcs.studio.core.YamcsPlugin.lambda$1(YamcsPlugin.java:131)
	at org.yamcs.studio.core.YamcsPlugin$$Lambda$19/42832559.processClientInfo(Unknown Source)
	at org.yamcs.studio.core.WebSocketRegistrar.lambda$5(WebSocketRegistrar.java:190)
	at org.yamcs.studio.core.WebSocketRegistrar$$Lambda$22/726410699.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.yamcs.studio.core.WebSocketRegistrar.onClientInfoData(WebSocketRegistrar.java:190)
	at org.yamcs.api.ws.WebSocketClientHandler.processSubscriptionData(WebSocketClientHandler.java:138)
	at org.yamcs.api.ws.WebSocketClientHandler.processFrame(WebSocketClientHandler.java:119)
	at org.yamcs.api.ws.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:96)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:103)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:153)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:122)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by fqqb** [comment]
Closing since i didn't see anything since, and the code has undergone many changes
